### PR TITLE
Assignment 2

### PR DESCRIPTION
**Pull request by silverspoon2000**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
reads, displays, and summarizes patient data. Then detect errors in the data.
## What did you learn from the changes you have made?
there may be a statistical function in numpy that can be used rather than using if/else statements to calculate mean, max, min
## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
see above
## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
no.
## How were these changes tested?
test with one data file, then add another another, before adding the entire dataset.
## Checklist
- [x] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by silverspoon2000** [comment]
note to self: git switch to old branch to prune branches, git push force to restart from correct branch,  git pull main to incorporate kaylie and daniel's changes from main, git add "file" to specifically resolve conflicts and overwrite (i.e. do not use git add -A). Do not manually resolve conflicts for Jupyter notebook as any changes in web editor would result in an invalid json file.

**Review by anjali-deshpande-hub — CHANGES_REQUESTED** [review]
Everything looks good, except one thing. 

There are changes to assignment_1.ipynb in this PR. Only changes to assignment_2.ipynb should be in this PR. Please correct that. Thanks!

**Comment by silverspoon2000** [comment]
Thanks for your comments, Anjali. Changes to assignment_1.ipynb has been reverted. This PR now only contains changes to Assignment_ipynb. Please review again.

**Comment by silverspoon2000** [comment]
Thanks for your comments, Anjali. Changes to assignment_1.ipynb has been reverted. This PR now only contains changes to Assignment_ipynb. Please review again. 

> Everything looks good, except one thing.
> 
> There are changes to assignment_1.ipynb in this PR. Only changes to assignment_2.ipynb should be in this PR. Please correct that. Thanks!

**Review by anjali-deshpande-hub — APPROVED** [review]
Perfect! Thank you!

**Pull request closed without merging**
